version: "3"

services:
  prometheus:
    image: quay.io/prometheus/prometheus:v2.25.0
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    - --web.console.libraries=/usr/share/prometheus/console_libraries
    - --web.console.templates=/usr/share/prometheus/consoles
    - --web.enable-lifecycle
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus-data:/prometheus
    user: nobody
    ports:
    - "9090:9090"
  prom-config-reload:
    image: quay.io/prometheus-operator/prometheus-config-reloader:v0.45.0
    command:
    - --watched-dir=/etc/config
    - --watch-interval=1m0s
    - --reload-url=http://prometheus:9090/-/reload
    volumes:
    - ./prometheus.yml:/etc/config/prometheus.yml
    depends_on:
    - prometheus
  demo-app:
    image: quay.io/prometheus/node-exporter:v1.1.1
    command:
    - --collector.disable-defaults
    - --web.disable-exporter-metrics
    - --collector.uname
    expose:
    - "9100"
volumes:
  prometheus-data:
