global:
  external_labels:
    foo: bar
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']
  - job_name: 'demo-app'
    dns_sd_configs:
      - names: ['demo-app']
        type: 'A'
        port: 9100
        refresh_interval: 10s
